spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/exchange
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            connection-timeout: 30000 # 30 seconds
            idle-timeout: 600000 # 10 minutes
            max-lifetime: 1800000 # 30 minutes
    jpa:
        hibernate:
            ddl-auto: update
            jdbc:
                batch_size: 50
        show-sql: false
        properties:
            hibernate:
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 50
                    batch_versioned_data: true
#    flyway:
#        enabled: true
#        baseline-on-migrate: true  # For existing databases
#        locations: classpath:db/migration

aws:
    region: eu-west-1
    endpoint: http://localhost:4566

app:
    sqs:
        queue-url: http://localhost:4566/000000000000/exchange-queue.fifo